kind: Pod
apiVersion: v1
metadata:
  name: ubuntu-compute-sf
spec:
  nodeSelector:
    "kubernetes.io/hostname": computesf
  containers:
    - name: ubuntu-compute-sf
      image: virtualhops/ato-ubuntu:latest
  restartPolicy: Never
