kind: Pod
apiVersion: v1
metadata:
  name: ubuntu-compute-la
spec:
  nodeSelector:
    "kubernetes.io/hostname": computela
  containers:
    - name: ubuntu-compute-la
      image: virtualhops/ato-ubuntu:latest
  restartPolicy: Never
